<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 5 Análisis bivariado | A Minimal Book Example</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 5 Análisis bivariado | A Minimal Book Example" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 5 Análisis bivariado | A Minimal Book Example" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="John Doe" />


<meta name="date" content="2026-02-27" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análisis-de-la-serie-de-tiempo..html"/>
<link rel="next" href="conclusión.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> About</a></li>
<li class="chapter" data-level="2" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>2</b> ANALISIS EXPLORATORIO DE DATOS</a>
<ul>
<li class="chapter" data-level="2.1" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#carga-del-dataset"><i class="fa fa-check"></i><b>2.1</b> CARGA DEL DATASET</a></li>
<li class="chapter" data-level="2.2" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#dimensi%C3%B3n-de-nuestro-dataset"><i class="fa fa-check"></i><b>2.2</b> Dimensión de nuestro dataset</a></li>
<li class="chapter" data-level="2.3" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#set-de-datos"><i class="fa fa-check"></i><b>2.3</b> Set de datos</a></li>
<li class="chapter" data-level="2.4" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#transformaci%C3%B3n-del-dataset"><i class="fa fa-check"></i><b>2.4</b> Transformación del dataset</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-univariado..html"><a href="análisis-univariado..html"><i class="fa fa-check"></i><b>3</b> Análisis univariado.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-categ%C3%B3rica"><i class="fa fa-check"></i><b>3.1</b> Análisis de las variables categórica</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#series.name"><i class="fa fa-check"></i><b>3.1.1</b> Series.name</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="análisis-univariado..html"><a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-numericas."><i class="fa fa-check"></i><b>3.2</b> Análisis de las variables numericas.</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#year"><i class="fa fa-check"></i><b>3.2.1</b> Year</a></li>
<li class="chapter" data-level="3.2.2" data-path="análisis-univariado..html"><a href="análisis-univariado..html#value"><i class="fa fa-check"></i><b>3.2.2</b> Value</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html"><i class="fa fa-check"></i><b>4</b> Análisis de la serie de tiempo.</a>
<ul>
<li class="chapter" data-level="4.1" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html#fecundidad-adolescente"><i class="fa fa-check"></i><b>4.1</b> Fecundidad adolescente</a></li>
<li class="chapter" data-level="4.2" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html#poblaci%C3%B3n-edad-00-mujeres"><i class="fa fa-check"></i><b>4.2</b> Población edad 00 – Mujeres</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="análisis-bivariado.html"><a href="análisis-bivariado.html"><i class="fa fa-check"></i><b>5</b> Análisis bivariado</a>
<ul>
<li class="chapter" data-level="5.1" data-path="análisis-bivariado.html"><a href="análisis-bivariado.html#prueba-con-rezagos"><i class="fa fa-check"></i><b>5.1</b> Prueba con rezagos</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="conclusión.html"><a href="conclusión.html"><i class="fa fa-check"></i><b>6</b> Conclusión</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Minimal Book Example</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-bivariado" class="section level1 hasAnchor" number="5">
<h1><span class="header-section-number">Chapter 5</span> Análisis bivariado<a href="análisis-bivariado.html#an%C3%A1lisis-bivariado" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div class="sourceCode" id="cb55"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb55-1"><a href="análisis-bivariado.html#cb55-1" tabindex="-1"></a><span class="co"># Relación entre fecundidad adolescente y población infantil</span></span>
<span id="cb55-2"><a href="análisis-bivariado.html#cb55-2" tabindex="-1"></a>df_relacion <span class="ot">&lt;-</span> df_3 <span class="sc">%&gt;%</span></span>
<span id="cb55-3"><a href="análisis-bivariado.html#cb55-3" tabindex="-1"></a>  <span class="fu">select</span>(Year, Series.Name, Value) <span class="sc">%&gt;%</span></span>
<span id="cb55-4"><a href="análisis-bivariado.html#cb55-4" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> Series.Name, <span class="at">values_from =</span> Value)</span>
<span id="cb55-5"><a href="análisis-bivariado.html#cb55-5" tabindex="-1"></a></span>
<span id="cb55-6"><a href="análisis-bivariado.html#cb55-6" tabindex="-1"></a><span class="co"># Renombrar columnas para facilitar</span></span>
<span id="cb55-7"><a href="análisis-bivariado.html#cb55-7" tabindex="-1"></a><span class="fu">colnames</span>(df_relacion) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;Year&quot;</span>, <span class="st">&quot;Fecundidad_Adolescente&quot;</span>, <span class="st">&quot;Poblacion_Femenina_0&quot;</span>, <span class="st">&quot;Poblacion_Masculina_0&quot;</span>)</span>
<span id="cb55-8"><a href="análisis-bivariado.html#cb55-8" tabindex="-1"></a></span>
<span id="cb55-9"><a href="análisis-bivariado.html#cb55-9" tabindex="-1"></a><span class="co"># Calcular población infantil total</span></span>
<span id="cb55-10"><a href="análisis-bivariado.html#cb55-10" tabindex="-1"></a>df_relacion<span class="sc">$</span>Poblacion_Infantil_Total <span class="ot">&lt;-</span> df_relacion<span class="sc">$</span>Poblacion_Femenina_0 <span class="sc">+</span> df_relacion<span class="sc">$</span>Poblacion_Masculina_0</span>
<span id="cb55-11"><a href="análisis-bivariado.html#cb55-11" tabindex="-1"></a></span>
<span id="cb55-12"><a href="análisis-bivariado.html#cb55-12" tabindex="-1"></a><span class="co"># Correlación</span></span>
<span id="cb55-13"><a href="análisis-bivariado.html#cb55-13" tabindex="-1"></a><span class="fu">cor.test</span>(df_relacion<span class="sc">$</span>Fecundidad_Adolescente, df_relacion<span class="sc">$</span>Poblacion_Infantil_Total, <span class="at">method =</span> <span class="st">&quot;pearson&quot;</span>)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df_relacion$Fecundidad_Adolescente and df_relacion$Poblacion_Infantil_Total
## t = 1.5622, df = 62, p-value = 0.1233
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.05377948  0.42030625
## sample estimates:
##       cor 
## 0.1946023</code></pre>
<div class="sourceCode" id="cb57"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb57-1"><a href="análisis-bivariado.html#cb57-1" tabindex="-1"></a><span class="co"># Visualizar relación</span></span>
<span id="cb57-2"><a href="análisis-bivariado.html#cb57-2" tabindex="-1"></a><span class="fu">ggplot</span>(df_relacion, <span class="fu">aes</span>(<span class="at">x =</span> Fecundidad_Adolescente, <span class="at">y =</span> Poblacion_Infantil_Total)) <span class="sc">+</span></span>
<span id="cb57-3"><a href="análisis-bivariado.html#cb57-3" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">color =</span> <span class="st">&quot;#1F4E79&quot;</span>, <span class="at">size =</span> <span class="dv">2</span>) <span class="sc">+</span></span>
<span id="cb57-4"><a href="análisis-bivariado.html#cb57-4" tabindex="-1"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">&quot;lm&quot;</span>, <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">color =</span> <span class="st">&quot;#F18F01&quot;</span>) <span class="sc">+</span></span>
<span id="cb57-5"><a href="análisis-bivariado.html#cb57-5" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb57-6"><a href="análisis-bivariado.html#cb57-6" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb57-7"><a href="análisis-bivariado.html#cb57-7" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Relación entre fecundidad adolescente y población infantil total&quot;</span>,</span>
<span id="cb57-8"><a href="análisis-bivariado.html#cb57-8" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Tasa de fecundidad adolescente&quot;</span>,</span>
<span id="cb57-9"><a href="análisis-bivariado.html#cb57-9" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Población infantil total (edad 0)&quot;</span></span>
<span id="cb57-10"><a href="análisis-bivariado.html#cb57-10" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## `geom_smooth()` using formula = &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 1 row containing non-finite outside the scale range (`stat_smooth()`).</code></pre>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range (`geom_point()`).</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-21-1.png" alt="" width="672" /></p>
<ul>
<li><p>0.1946 es una correlación positiva muy débil,indica que existe una leve tendencia a que cuando aumenta la fecundidad adolescente, también aumente la población infantil total, pero la relación es muy tenue.</p></li>
<li><p>p = 0.1233 &gt; 0.05, No hay evidencia estadísticamente significativa para afirmar que existe una correlación entre la fecundidad adolescente y la población infantil total en Colombia durante el período analizado.</p></li>
<li><p>El intervalo inluye el 0 así que no podemos asegurar si la relación es positiva, negativa o inexistente.</p></li>
</ul>
<p>En conclusión, no existe una relación lineal estadísticamente significativa entre la fecundidad adolescente y la población infantil total en Colombia entre 1960 y 2024.</p>
<p>Esto puede deberse a:</p>
<p>La fecundidad adolescente es solo una parte de la fecundidad total. Las mujeres adultas (20+ años) aportan muchos más nacimientos.</p>
<p>Cambios demográficos estructurales: La población infantil total está influenciada por múltiples factores (fecundidad general, mortalidad infantil, migración, etc.).</p>
<div id="prueba-con-rezagos" class="section level2 hasAnchor" number="5.1">
<h2><span class="header-section-number">5.1</span> Prueba con rezagos<a href="análisis-bivariado.html#prueba-con-rezagos" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El objetivo fundamental de aplicar rezagos es entender relaciones de causa-efecto a lo largo del tiempo</p>
<div class="sourceCode" id="cb61"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb61-1"><a href="análisis-bivariado.html#cb61-1" tabindex="-1"></a><span class="co"># Crear rezagos de 5, 10 y 15 años</span></span>
<span id="cb61-2"><a href="análisis-bivariado.html#cb61-2" tabindex="-1"></a>df_rezagos <span class="ot">&lt;-</span> df_relacion <span class="sc">%&gt;%</span></span>
<span id="cb61-3"><a href="análisis-bivariado.html#cb61-3" tabindex="-1"></a>  <span class="fu">arrange</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb61-4"><a href="análisis-bivariado.html#cb61-4" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb61-5"><a href="análisis-bivariado.html#cb61-5" tabindex="-1"></a>    <span class="at">Fecundidad_lag5 =</span> <span class="fu">lag</span>(Fecundidad_Adolescente, <span class="dv">5</span>),</span>
<span id="cb61-6"><a href="análisis-bivariado.html#cb61-6" tabindex="-1"></a>    <span class="at">Fecundidad_lag10 =</span> <span class="fu">lag</span>(Fecundidad_Adolescente, <span class="dv">10</span>),</span>
<span id="cb61-7"><a href="análisis-bivariado.html#cb61-7" tabindex="-1"></a>    <span class="at">Fecundidad_lag15 =</span> <span class="fu">lag</span>(Fecundidad_Adolescente, <span class="dv">15</span>)</span>
<span id="cb61-8"><a href="análisis-bivariado.html#cb61-8" tabindex="-1"></a>  )</span>
<span id="cb61-9"><a href="análisis-bivariado.html#cb61-9" tabindex="-1"></a></span>
<span id="cb61-10"><a href="análisis-bivariado.html#cb61-10" tabindex="-1"></a><span class="co"># Correlación con rezago 5</span></span>
<span id="cb61-11"><a href="análisis-bivariado.html#cb61-11" tabindex="-1"></a><span class="fu">cor.test</span>(df_rezagos<span class="sc">$</span>Fecundidad_lag5, df_rezagos<span class="sc">$</span>Poblacion_Infantil_Total)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df_rezagos$Fecundidad_lag5 and df_rezagos$Poblacion_Infantil_Total
## t = 1.1757, df = 58, p-value = 0.2445
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.1054385  0.3913349
## sample estimates:
##       cor 
## 0.1525711</code></pre>
<div class="sourceCode" id="cb63"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb63-1"><a href="análisis-bivariado.html#cb63-1" tabindex="-1"></a><span class="co"># Correlación con rezago 10  </span></span>
<span id="cb63-2"><a href="análisis-bivariado.html#cb63-2" tabindex="-1"></a><span class="fu">cor.test</span>(df_rezagos<span class="sc">$</span>Fecundidad_lag10, df_rezagos<span class="sc">$</span>Poblacion_Infantil_Total)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df_rezagos$Fecundidad_lag10 and df_rezagos$Poblacion_Infantil_Total
## t = -1.3275, df = 53, p-value = 0.19
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.42448736  0.09019735
## sample estimates:
##        cor 
## -0.1793925</code></pre>
<div class="sourceCode" id="cb65"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb65-1"><a href="análisis-bivariado.html#cb65-1" tabindex="-1"></a><span class="co"># Correlación con rezago 15</span></span>
<span id="cb65-2"><a href="análisis-bivariado.html#cb65-2" tabindex="-1"></a><span class="fu">cor.test</span>(df_rezagos<span class="sc">$</span>Fecundidad_lag15, df_rezagos<span class="sc">$</span>Poblacion_Infantil_Total)</span></code></pre></div>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  df_rezagos$Fecundidad_lag15 and df_rezagos$Poblacion_Infantil_Total
## t = -2.3061, df = 48, p-value = 0.02547
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  -0.54615626 -0.04108378
## sample estimates:
##        cor 
## -0.3158199</code></pre>
<ul>
<li>Rezago de 5 años:</li>
</ul>
<p>Correlación positiva muy débil</p>
<p>No significativa (p &gt; 0.05)</p>
<p>El intervalo incluye al cero → no podemos concluir nada</p>
<ul>
<li>Rezago de 10 años:</li>
</ul>
<p>Correlación negativa débil</p>
<p>No significativa (p &gt; 0.05)</p>
<p>Intervalo cruza cero (apenas)</p>
<ul>
<li>Rezago de 15 años:</li>
</ul>
<p>Correlación negativa moderada</p>
<p>Sí es estadísticamente significativa (p &lt; 0.05)</p>
<p>r = -0.3158 indica que a mayor fecundidad adolescente hoy, menor población infantil total 15 años después (o viceversa).</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análisis-de-la-serie-de-tiempo..html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="conclusión.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/04-bivariado.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
