<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 2 Análisis univariado. | A Minimal Book Example</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 2 Análisis univariado. | A Minimal Book Example" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 2 Análisis univariado. | A Minimal Book Example" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="John Doe" />


<meta name="date" content="2026-02-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="analisis-exploratorio-de-datos.html"/>
<link rel="next" href="análisis-de-la-serie-de-tiempo..html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>1</b> ANALISIS EXPLORATORIO DE DATOS</a>
<ul>
<li class="chapter" data-level="1.1" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#carga-del-dataset"><i class="fa fa-check"></i><b>1.1</b> CARGA DEL DATASET</a></li>
<li class="chapter" data-level="1.2" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#dimensi%C3%B3n-de-nuestro-dataset"><i class="fa fa-check"></i><b>1.2</b> Dimensión de nuestro dataset</a></li>
<li class="chapter" data-level="1.3" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#set-de-datos"><i class="fa fa-check"></i><b>1.3</b> Set de datos</a></li>
<li class="chapter" data-level="1.4" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#transformaci%C3%B3n-del-dataset"><i class="fa fa-check"></i><b>1.4</b> Transformación del dataset</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-univariado..html"><a href="análisis-univariado..html"><i class="fa fa-check"></i><b>2</b> Análisis univariado.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-categ%C3%B3rica"><i class="fa fa-check"></i><b>2.1</b> Análisis de las variables categórica</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#series.name"><i class="fa fa-check"></i><b>2.1.1</b> Series.name</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="análisis-univariado..html"><a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-numericas."><i class="fa fa-check"></i><b>2.2</b> Análisis de las variables numericas.</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#value"><i class="fa fa-check"></i><b>2.2.1</b> Value</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html"><i class="fa fa-check"></i><b>3</b> Análisis de la serie de tiempo.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html#fecundidad-adolescente"><i class="fa fa-check"></i><b>3.1</b> Fecundidad adolescente</a></li>
<li class="chapter" data-level="3.2" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html#poblaci%C3%B3n-edad-00-mujeres"><i class="fa fa-check"></i><b>3.2</b> Población edad 00 – Mujeres</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-bivariado.html"><a href="análisis-bivariado.html"><i class="fa fa-check"></i><b>4</b> Análisis bivariado</a>
<ul>
<li class="chapter" data-level="4.1" data-path="análisis-bivariado.html"><a href="análisis-bivariado.html#prueba-con-rezagos"><i class="fa fa-check"></i><b>4.1</b> Prueba con rezagos</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="conclusión.html"><a href="conclusión.html"><i class="fa fa-check"></i><b>5</b> Conclusión</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Minimal Book Example</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-univariado." class="section level1 hasAnchor" number="2">
<h1><span class="header-section-number">Chapter 2</span> Análisis univariado.<a href="análisis-univariado..html#an%C3%A1lisis-univariado." class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Analicemos las carateristicas generales de cada variable de nuestro set de datos.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="análisis-univariado..html#cb10-1" tabindex="-1"></a><span class="fu">str</span>(df_long)</span></code></pre></div>
<pre><code>## tibble [30,810 × 3] (S3: tbl_df/tbl/data.frame)
##  $ Series.Name: chr [1:30810] &quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot; &quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot; &quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot; &quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot; ...
##  $ Year       : Date[1:30810], format: &quot;1960-01-01&quot; &quot;1961-01-01&quot; &quot;1962-01-01&quot; ...
##  $ Value      : num [1:30810] 115 114 112 110 108 ...</code></pre>
<div id="análisis-de-las-variables-categórica" class="section level2 hasAnchor" number="2.1">
<h2><span class="header-section-number">2.1</span> Análisis de las variables categórica<a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-categ%C3%B3rica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="series.name" class="section level3 hasAnchor" number="2.1.1">
<h3><span class="header-section-number">2.1.1</span> Series.name<a href="análisis-univariado..html#series.name" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="análisis-univariado..html#cb12-1" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb12-2"><a href="análisis-univariado..html#cb12-2" tabindex="-1"></a></span>
<span id="cb12-3"><a href="análisis-univariado..html#cb12-3" tabindex="-1"></a><span class="co">#  Calcular cobertura porcentual por indicador</span></span>
<span id="cb12-4"><a href="análisis-univariado..html#cb12-4" tabindex="-1"></a>frecuencia_indicadores <span class="ot">&lt;-</span> df_long <span class="sc">%&gt;%</span></span>
<span id="cb12-5"><a href="análisis-univariado..html#cb12-5" tabindex="-1"></a>  <span class="fu">group_by</span>(Series.Name) <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="análisis-univariado..html#cb12-6" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb12-7"><a href="análisis-univariado..html#cb12-7" tabindex="-1"></a>    <span class="at">total_registros =</span> <span class="fu">n</span>(),                     <span class="co"># Total de años posibles</span></span>
<span id="cb12-8"><a href="análisis-univariado..html#cb12-8" tabindex="-1"></a>    años<span class="at">_con_datos =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(Value)),       <span class="co"># Años con datos reales</span></span>
<span id="cb12-9"><a href="análisis-univariado..html#cb12-9" tabindex="-1"></a>    años<span class="at">_sin_datos =</span> <span class="fu">sum</span>(<span class="fu">is.na</span>(Value)),        <span class="co"># Años sin datos</span></span>
<span id="cb12-10"><a href="análisis-univariado..html#cb12-10" tabindex="-1"></a>    <span class="at">porcentaje_cobertura =</span> <span class="fu">round</span>((años_con_datos <span class="sc">/</span> total_registros) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>)</span>
<span id="cb12-11"><a href="análisis-univariado..html#cb12-11" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb12-12"><a href="análisis-univariado..html#cb12-12" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(porcentaje_cobertura))</span>
<span id="cb12-13"><a href="análisis-univariado..html#cb12-13" tabindex="-1"></a></span>
<span id="cb12-14"><a href="análisis-univariado..html#cb12-14" tabindex="-1"></a><span class="co"># Ver los primeros indicadores con mayor cobertura</span></span>
<span id="cb12-15"><a href="análisis-univariado..html#cb12-15" tabindex="-1"></a><span class="fu">head</span>(frecuencia_indicadores)</span></code></pre></div>
<pre><code>## # A tibble: 6 × 5
##   Series.Name                   total_registros `años_con_datos` `años_sin_datos` porcentaje_cobertura
##   &lt;chr&gt;                                   &lt;int&gt;            &lt;int&gt;            &lt;int&gt;                &lt;dbl&gt;
## 1 Age dependency ratio (% of w…              65               65                0                  100
## 2 Age dependency ratio, old                  65               65                0                  100
## 3 Age dependency ratio, young                65               65                0                  100
## 4 Age population, age 00, fema…              65               65                0                  100
## 5 Age population, age 00, male               65               65                0                  100
## 6 Age population, age 01, fema…              65               65                0                  100</code></pre>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="análisis-univariado..html#cb14-1" tabindex="-1"></a><span class="co"># Clasificación por porcentaje</span></span>
<span id="cb14-2"><a href="análisis-univariado..html#cb14-2" tabindex="-1"></a>df_categorias <span class="ot">&lt;-</span> frecuencia_indicadores <span class="sc">%&gt;%</span></span>
<span id="cb14-3"><a href="análisis-univariado..html#cb14-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-4"><a href="análisis-univariado..html#cb14-4" tabindex="-1"></a>    <span class="at">categoria =</span> <span class="fu">case_when</span>(</span>
<span id="cb14-5"><a href="análisis-univariado..html#cb14-5" tabindex="-1"></a>      porcentaje_cobertura <span class="sc">&gt;=</span> <span class="dv">80</span> <span class="sc">~</span> <span class="st">&quot;Alta cobertura (≥80%)&quot;</span>,</span>
<span id="cb14-6"><a href="análisis-univariado..html#cb14-6" tabindex="-1"></a>      porcentaje_cobertura <span class="sc">&gt;=</span> <span class="dv">50</span> <span class="sc">~</span> <span class="st">&quot;Cobertura media (50–79%)&quot;</span>,</span>
<span id="cb14-7"><a href="análisis-univariado..html#cb14-7" tabindex="-1"></a>      <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&quot;Baja cobertura (&lt;50%)&quot;</span></span>
<span id="cb14-8"><a href="análisis-univariado..html#cb14-8" tabindex="-1"></a>    )</span>
<span id="cb14-9"><a href="análisis-univariado..html#cb14-9" tabindex="-1"></a>  ) <span class="sc">%&gt;%</span></span>
<span id="cb14-10"><a href="análisis-univariado..html#cb14-10" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb14-11"><a href="análisis-univariado..html#cb14-11" tabindex="-1"></a>    <span class="at">categoria =</span> <span class="fu">factor</span>(categoria,</span>
<span id="cb14-12"><a href="análisis-univariado..html#cb14-12" tabindex="-1"></a>                       <span class="at">levels =</span> <span class="fu">c</span>(<span class="st">&quot;Alta cobertura (&gt;=80%)&quot;</span>,</span>
<span id="cb14-13"><a href="análisis-univariado..html#cb14-13" tabindex="-1"></a>                                  <span class="st">&quot;Cobertura media (50–79%)&quot;</span>,</span>
<span id="cb14-14"><a href="análisis-univariado..html#cb14-14" tabindex="-1"></a>                                  <span class="st">&quot;Baja cobertura (&lt;50%)&quot;</span>))</span>
<span id="cb14-15"><a href="análisis-univariado..html#cb14-15" tabindex="-1"></a>  )</span>
<span id="cb14-16"><a href="análisis-univariado..html#cb14-16" tabindex="-1"></a>resumen_categorias <span class="ot">&lt;-</span> df_categorias <span class="sc">%&gt;%</span></span>
<span id="cb14-17"><a href="análisis-univariado..html#cb14-17" tabindex="-1"></a>  <span class="fu">group_by</span>(categoria) <span class="sc">%&gt;%</span></span>
<span id="cb14-18"><a href="análisis-univariado..html#cb14-18" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">n =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb14-19"><a href="análisis-univariado..html#cb14-19" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">porcentaje =</span> <span class="fu">round</span>(n <span class="sc">/</span> <span class="fu">sum</span>(n) <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>))</span>
<span id="cb14-20"><a href="análisis-univariado..html#cb14-20" tabindex="-1"></a></span>
<span id="cb14-21"><a href="análisis-univariado..html#cb14-21" tabindex="-1"></a><span class="fu">print</span>(resumen_categorias)</span></code></pre></div>
<pre><code>## # A tibble: 3 × 3
##   categoria                           n porcentaje
##   &lt;fct&gt;                           &lt;int&gt;      &lt;dbl&gt;
## 1 &quot;Cobertura media (50\u201379%)&quot;    67       14.1
## 2 &quot;Baja cobertura (&lt;50%)&quot;           226       47.7
## 3  &lt;NA&gt;                             181       38.2</code></pre>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="análisis-univariado..html#cb16-1" tabindex="-1"></a><span class="fu">ggplot</span>(resumen_categorias, <span class="fu">aes</span>(<span class="at">x =</span> categoria, <span class="at">y =</span> n, <span class="at">fill =</span> categoria)) <span class="sc">+</span></span>
<span id="cb16-2"><a href="análisis-univariado..html#cb16-2" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="at">width =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb16-3"><a href="análisis-univariado..html#cb16-3" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label =</span> <span class="fu">paste0</span>(n, <span class="st">&quot; (&quot;</span>, porcentaje, <span class="st">&quot;%)&quot;</span>)), </span>
<span id="cb16-4"><a href="análisis-univariado..html#cb16-4" tabindex="-1"></a>            <span class="at">vjust =</span> <span class="sc">-</span><span class="fl">0.5</span>, </span>
<span id="cb16-5"><a href="análisis-univariado..html#cb16-5" tabindex="-1"></a>            <span class="at">size =</span> <span class="dv">4</span>,</span>
<span id="cb16-6"><a href="análisis-univariado..html#cb16-6" tabindex="-1"></a>            <span class="at">fontface =</span> <span class="st">&quot;bold&quot;</span>) <span class="sc">+</span></span>
<span id="cb16-7"><a href="análisis-univariado..html#cb16-7" tabindex="-1"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(</span>
<span id="cb16-8"><a href="análisis-univariado..html#cb16-8" tabindex="-1"></a>    <span class="st">&quot;Alta cobertura (≥80%)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#1F4E79&quot;</span>,</span>
<span id="cb16-9"><a href="análisis-univariado..html#cb16-9" tabindex="-1"></a>    <span class="st">&quot;Cobertura media (50–79%)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#4A7A9C&quot;</span>,</span>
<span id="cb16-10"><a href="análisis-univariado..html#cb16-10" tabindex="-1"></a>    <span class="st">&quot;Baja cobertura (&lt;50%)&quot;</span> <span class="ot">=</span> <span class="st">&quot;#7BA0B9&quot;</span></span>
<span id="cb16-11"><a href="análisis-univariado..html#cb16-11" tabindex="-1"></a>  )) <span class="sc">+</span></span>
<span id="cb16-12"><a href="análisis-univariado..html#cb16-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb16-13"><a href="análisis-univariado..html#cb16-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb16-14"><a href="análisis-univariado..html#cb16-14" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">16</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>),</span>
<span id="cb16-15"><a href="análisis-univariado..html#cb16-15" tabindex="-1"></a>    <span class="at">plot.subtitle =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">color =</span> <span class="st">&quot;gray50&quot;</span>),</span>
<span id="cb16-16"><a href="análisis-univariado..html#cb16-16" tabindex="-1"></a>    <span class="at">axis.title =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">12</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>),</span>
<span id="cb16-17"><a href="análisis-univariado..html#cb16-17" tabindex="-1"></a>    <span class="at">axis.text =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">11</span>),</span>
<span id="cb16-18"><a href="análisis-univariado..html#cb16-18" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;none&quot;</span>,</span>
<span id="cb16-19"><a href="análisis-univariado..html#cb16-19" tabindex="-1"></a>    <span class="at">panel.grid.major.x =</span> <span class="fu">element_blank</span>(),</span>
<span id="cb16-20"><a href="análisis-univariado..html#cb16-20" tabindex="-1"></a>    <span class="at">panel.grid.minor =</span> <span class="fu">element_blank</span>()</span>
<span id="cb16-21"><a href="análisis-univariado..html#cb16-21" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb16-22"><a href="análisis-univariado..html#cb16-22" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb16-23"><a href="análisis-univariado..html#cb16-23" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Clasificación de indicadores según cobertura temporal&quot;</span>,</span>
<span id="cb16-24"><a href="análisis-univariado..html#cb16-24" tabindex="-1"></a>    <span class="at">subtitle =</span> <span class="st">&quot;Criterio basado en porcentaje de datos disponibles (1960–2024)&quot;</span>,</span>
<span id="cb16-25"><a href="análisis-univariado..html#cb16-25" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Nivel de cobertura&quot;</span>,</span>
<span id="cb16-26"><a href="análisis-univariado..html#cb16-26" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Número de indicadores&quot;</span></span>
<span id="cb16-27"><a href="análisis-univariado..html#cb16-27" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-6-1.png" alt="" width="672" /></p>
<p>El análisis de cobertura temporal revela que el 47.7% de los indicadores presenta baja cobertura (&lt;50%), lo que indica una disponibilidad limitada de datos a lo largo del período 1960–2024. Esto sugiere que una proporción considerable de indicadores no cuenta con suficiente respaldo histórico para realizar análisis de tendencia de largo plazo.</p>
<p>Por otro lado, el 38.2% de los indicadores muestra alta cobertura (≥80%), lo que garantiza una base sólida para estudios longitudinales y análisis comparativos en el tiempo.</p>
<p>Estos resultados evidencian que, aunque el dataset es amplio en términos de cantidad de indicadores, la calidad y continuidad temporal de la información es heterogénea.Por lo tanto, para los análisis posteriores se priorizarán los indicadores con alta cobertura, con el fin de asegurar mayor consistencia y confiabilidad en los resultados.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb17-1"><a href="análisis-univariado..html#cb17-1" tabindex="-1"></a><span class="co"># Filtrar solo indicadores de alta cobertura (&gt;50 años con datos)</span></span>
<span id="cb17-2"><a href="análisis-univariado..html#cb17-2" tabindex="-1"></a>indicadores_alta_cobertura <span class="ot">&lt;-</span> frecuencia_indicadores <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="análisis-univariado..html#cb17-3" tabindex="-1"></a>  <span class="fu">filter</span>(años_con_datos <span class="sc">&gt;</span> <span class="dv">50</span>)</span>
<span id="cb17-4"><a href="análisis-univariado..html#cb17-4" tabindex="-1"></a></span>
<span id="cb17-5"><a href="análisis-univariado..html#cb17-5" tabindex="-1"></a><span class="co"># Ver cuántos indicadores de alta cobertura tenemos</span></span>
<span id="cb17-6"><a href="análisis-univariado..html#cb17-6" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Número de indicadores de alta cobertura:&quot;</span>, <span class="fu">nrow</span>(indicadores_alta_cobertura))</span></code></pre></div>
<pre><code>## Número de indicadores de alta cobertura: 181</code></pre>
<div class="sourceCode" id="cb19"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb19-1"><a href="análisis-univariado..html#cb19-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Porcentaje del total:&quot;</span>, <span class="fu">round</span>(<span class="fu">nrow</span>(indicadores_alta_cobertura)<span class="sc">/</span><span class="fu">nrow</span>(frecuencia_indicadores)<span class="sc">*</span><span class="dv">100</span>, <span class="dv">2</span>), <span class="st">&quot;%&quot;</span>)</span></code></pre></div>
<pre><code>## Porcentaje del total: 38.19 %</code></pre>
<div class="sourceCode" id="cb21"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb21-1"><a href="análisis-univariado..html#cb21-1" tabindex="-1"></a><span class="co"># Ver los nombres de los indicadores de alta cobertura</span></span>
<span id="cb21-2"><a href="análisis-univariado..html#cb21-2" tabindex="-1"></a></span>
<span id="cb21-3"><a href="análisis-univariado..html#cb21-3" tabindex="-1"></a><span class="co"># Si quieres crear un nuevo dataframe SOLO con los datos de estos indicadores</span></span>
<span id="cb21-4"><a href="análisis-univariado..html#cb21-4" tabindex="-1"></a>df_alta_cobertura <span class="ot">&lt;-</span> df_long <span class="sc">%&gt;%</span></span>
<span id="cb21-5"><a href="análisis-univariado..html#cb21-5" tabindex="-1"></a>  <span class="fu">filter</span>(Series.Name <span class="sc">%in%</span> indicadores_alta_cobertura<span class="sc">$</span>Series.Name)</span>
<span id="cb21-6"><a href="análisis-univariado..html#cb21-6" tabindex="-1"></a></span>
<span id="cb21-7"><a href="análisis-univariado..html#cb21-7" tabindex="-1"></a><span class="co"># Reemplazar df_long por la versión filtrada</span></span>
<span id="cb21-8"><a href="análisis-univariado..html#cb21-8" tabindex="-1"></a>df_long <span class="ot">&lt;-</span> df_alta_cobertura</span></code></pre></div>
<p>Tras aplicar el criterio de selección, el conjunto de datos se reduce de 474 a 181 indicadores, lo que representa una depuración del 61.8% de los indicadores originales. Este filtrado mejora la calidad del análisis al concentrarse en variables con suficiente continuidad temporal.</p>
<p>El gráfico de barras muestra la frecuencia de registros por indicador dentro del conjunto de datos. Se observa que los principales indicadores presentan una frecuencia de 65 observaciones cada uno, lo que sugiere que cuentan con información anual completa para el período analizado.</p>
</div>
</div>
<div id="análisis-de-las-variables-numericas." class="section level2 hasAnchor" number="2.2">
<h2><span class="header-section-number">2.2</span> Análisis de las variables numericas.<a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-numericas." class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>###Year</p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="análisis-univariado..html#cb22-1" tabindex="-1"></a><span class="fu">summary</span>(df_long<span class="sc">$</span>Year)</span></code></pre></div>
<pre><code>##         Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
## &quot;1960-01-01&quot; &quot;1976-01-01&quot; &quot;1992-01-01&quot; &quot;1992-01-01&quot; &quot;2008-01-01&quot; &quot;2024-01-01&quot;</code></pre>
<p>La variable Year presenta un rango entre 1960 y 2024. La coincidencia entre media y mediana (1992) indica una distribución temporal simétrica, sin concentración excesiva en años específicos dentro del período analizado.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="análisis-univariado..html#cb24-1" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb24-2"><a href="análisis-univariado..html#cb24-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb24-3"><a href="análisis-univariado..html#cb24-3" tabindex="-1"></a></span>
<span id="cb24-4"><a href="análisis-univariado..html#cb24-4" tabindex="-1"></a>datos_por_anio <span class="ot">&lt;-</span> df_long <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="análisis-univariado..html#cb24-5" tabindex="-1"></a>  <span class="fu">group_by</span>(Year) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="análisis-univariado..html#cb24-6" tabindex="-1"></a>  <span class="fu">summarise</span>(</span>
<span id="cb24-7"><a href="análisis-univariado..html#cb24-7" tabindex="-1"></a>    <span class="at">datos_disponibles =</span> <span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(Value))</span>
<span id="cb24-8"><a href="análisis-univariado..html#cb24-8" tabindex="-1"></a>  )</span>
<span id="cb24-9"><a href="análisis-univariado..html#cb24-9" tabindex="-1"></a></span>
<span id="cb24-10"><a href="análisis-univariado..html#cb24-10" tabindex="-1"></a><span class="fu">ggplot</span>(datos_por_anio, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> datos_disponibles)) <span class="sc">+</span></span>
<span id="cb24-11"><a href="análisis-univariado..html#cb24-11" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;#1F4E79&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb24-12"><a href="análisis-univariado..html#cb24-12" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb24-13"><a href="análisis-univariado..html#cb24-13" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb24-14"><a href="análisis-univariado..html#cb24-14" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Disponibilidad de datos por año &quot;</span>,</span>
<span id="cb24-15"><a href="análisis-univariado..html#cb24-15" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Año&quot;</span>,</span>
<span id="cb24-16"><a href="análisis-univariado..html#cb24-16" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Número de registros disponibles&quot;</span></span>
<span id="cb24-17"><a href="análisis-univariado..html#cb24-17" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-9-1.png" alt="" width="672" /></p>
<div id="value" class="section level3 hasAnchor" number="2.2.1">
<h3><span class="header-section-number">2.2.1</span> Value<a href="análisis-univariado..html#value" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="análisis-univariado..html#cb25-1" tabindex="-1"></a><span class="fu">summary</span>(df_long<span class="sc">$</span>Value)</span></code></pre></div>
<pre><code>##     Min.  1st Qu.   Median     Mean  3rd Qu.     Max.     NA&#39;s 
##   -98057       15   209957  1226070   418892 52886363       31</code></pre>
<p>El análisis descriptivo de la variable Value muestra una alta dispersión en los datos. El valor mínimo registrado es de -98.057, mientras que el valor máximo alcanza 52.886.363, lo que evidencia una amplitud considerable entre los indicadores analizados.</p>
<p>La media (1.226.070) es significativamente mayor que la mediana (209.957), lo que indica una fuerte asimetría positiva en la distribución. Esto sugiere la presencia de valores extremadamente altos que influyen en el promedio, mientras que la mayoría de las observaciones se concentra en magnitudes considerablemente menores.</p>
<p>El primer cuartil (15) y el tercer cuartil (418.892) muestran que el 50% central de los datos se ubica en un rango amplio, lo cual refleja la coexistencia de indicadores medidos en distintas escalas y unidades. En consecuencia, la variable no puede interpretarse como una medida homogénea, sino como la agregación de múltiples fenómenos demográficos y de salud.</p>
<p>Finalmente, se identificaron 31 valores faltantes (NA) dentro del subconjunto de indicadores de alta cobertura, lo que representa una proporción reducida en comparación con el total de observaciones filtradas.</p>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="análisis-univariado..html#cb27-1" tabindex="-1"></a><span class="co">#Veamos que indicador nos arroja ese valor negativo alto.</span></span>
<span id="cb27-2"><a href="análisis-univariado..html#cb27-2" tabindex="-1"></a>df_long <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="análisis-univariado..html#cb27-3" tabindex="-1"></a>  <span class="fu">filter</span>(Value <span class="sc">==</span> <span class="fu">min</span>(Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span></code></pre></div>
<pre><code>## # A tibble: 1 × 3
##   Series.Name   Year        Value
##   &lt;chr&gt;         &lt;date&gt;      &lt;dbl&gt;
## 1 Net migration 1976-01-01 -98057</code></pre>
<p>El valor mínimo observado (-98.057) corresponde al indicador de migración neta en el año 1976. Este valor negativo indica que, durante ese año, Colombia registró una mayor cantidad de emigrantes que inmigrantes.</p>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="análisis-univariado..html#cb29-1" tabindex="-1"></a><span class="fu">ggplot</span>(df_long, <span class="fu">aes</span>(<span class="at">x =</span> Value)) <span class="sc">+</span></span>
<span id="cb29-2"><a href="análisis-univariado..html#cb29-2" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">30</span>, <span class="at">fill =</span> <span class="st">&quot;#6baed6&quot;</span>, <span class="at">color =</span> <span class="st">&quot;white&quot;</span>) <span class="sc">+</span></span>
<span id="cb29-3"><a href="análisis-univariado..html#cb29-3" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb29-4"><a href="análisis-univariado..html#cb29-4" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Distribución General de la Variable Value&quot;</span>,</span>
<span id="cb29-5"><a href="análisis-univariado..html#cb29-5" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Valor&quot;</span>,</span>
<span id="cb29-6"><a href="análisis-univariado..html#cb29-6" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Frecuencia&quot;</span></span>
<span id="cb29-7"><a href="análisis-univariado..html#cb29-7" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb29-8"><a href="análisis-univariado..html#cb29-8" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb29-9"><a href="análisis-univariado..html#cb29-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb29-10"><a href="análisis-univariado..html#cb29-10" tabindex="-1"></a>    <span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>)</span>
<span id="cb29-11"><a href="análisis-univariado..html#cb29-11" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Warning: Removed 31 rows containing non-finite outside the scale range (`stat_bin()`).</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-12-1.png" alt="" width="672" /></p>
<p>La distribución general de la variable Value muestra una marcada asimetría positiva. La mayor parte de las observaciones se concentra en valores bajos, cercanos a cero, mientras que un número reducido de registros alcanza magnitudes extremadamente altas, generando una cola larga hacia la derecha. Esta concentración provoca que el histograma se vea comprimido en el extremo inferior del eje horizontal, dificultando la visualización detallada de la mayoría de los datos. Este comportamiento es consistente con la diferencia observada entre la media y la mediana, y refleja la coexistencia de indicadores medidos en escalas muy distintas dentro del mismo conjunto de datos. Por lo tanto, no es apropiado interpretar esta variable de manera agregada, siendo más adecuado analizar cada indicador de forma individual.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="analisis-exploratorio-de-datos.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-de-la-serie-de-tiempo..html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/02-univariado.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
