<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 3 Análisis de la serie de tiempo. | A Minimal Book Example</title>
  <meta name="description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 3 Análisis de la serie de tiempo. | A Minimal Book Example" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 3 Análisis de la serie de tiempo. | A Minimal Book Example" />
  
  <meta name="twitter:description" content="<p>This is a minimal example of using the bookdown package to write a book.
The HTML output format for this example is bookdown::gitbook,
set in the _output.yml file.</p>" />
  

<meta name="author" content="John Doe" />


<meta name="date" content="2026-02-24" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="análisis-univariado..html"/>
<link rel="next" href="análisis-bivariado.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">A Minimal Book Example</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html"><i class="fa fa-check"></i><b>1</b> ANALISIS EXPLORATORIO DE DATOS</a>
<ul>
<li class="chapter" data-level="1.1" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#carga-del-dataset"><i class="fa fa-check"></i><b>1.1</b> CARGA DEL DATASET</a></li>
<li class="chapter" data-level="1.2" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#dimensi%C3%B3n-de-nuestro-dataset"><i class="fa fa-check"></i><b>1.2</b> Dimensión de nuestro dataset</a></li>
<li class="chapter" data-level="1.3" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#set-de-datos"><i class="fa fa-check"></i><b>1.3</b> Set de datos</a></li>
<li class="chapter" data-level="1.4" data-path="analisis-exploratorio-de-datos.html"><a href="analisis-exploratorio-de-datos.html#transformaci%C3%B3n-del-dataset"><i class="fa fa-check"></i><b>1.4</b> Transformación del dataset</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="análisis-univariado..html"><a href="análisis-univariado..html"><i class="fa fa-check"></i><b>2</b> Análisis univariado.</a>
<ul>
<li class="chapter" data-level="2.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-categ%C3%B3rica"><i class="fa fa-check"></i><b>2.1</b> Análisis de las variables categórica</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#series.name"><i class="fa fa-check"></i><b>2.1.1</b> Series.name</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="análisis-univariado..html"><a href="análisis-univariado..html#an%C3%A1lisis-de-las-variables-numericas."><i class="fa fa-check"></i><b>2.2</b> Análisis de las variables numericas.</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="análisis-univariado..html"><a href="análisis-univariado..html#value"><i class="fa fa-check"></i><b>2.2.1</b> Value</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="3" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html"><i class="fa fa-check"></i><b>3</b> Análisis de la serie de tiempo.</a>
<ul>
<li class="chapter" data-level="3.1" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html#fecundidad-adolescente"><i class="fa fa-check"></i><b>3.1</b> Fecundidad adolescente</a></li>
<li class="chapter" data-level="3.2" data-path="análisis-de-la-serie-de-tiempo..html"><a href="análisis-de-la-serie-de-tiempo..html#poblaci%C3%B3n-edad-00-mujeres"><i class="fa fa-check"></i><b>3.2</b> Población edad 00 – Mujeres</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="análisis-bivariado.html"><a href="análisis-bivariado.html"><i class="fa fa-check"></i><b>4</b> Análisis bivariado</a>
<ul>
<li class="chapter" data-level="4.1" data-path="análisis-bivariado.html"><a href="análisis-bivariado.html#prueba-con-rezagos"><i class="fa fa-check"></i><b>4.1</b> Prueba con rezagos</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="conclusión.html"><a href="conclusión.html"><i class="fa fa-check"></i><b>5</b> Conclusión</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">A Minimal Book Example</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="análisis-de-la-serie-de-tiempo." class="section level1 hasAnchor" number="3">
<h1><span class="header-section-number">Chapter 3</span> Análisis de la serie de tiempo.<a href="análisis-de-la-serie-de-tiempo..html#an%C3%A1lisis-de-la-serie-de-tiempo." class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Con el fin de realizar un análisis más profundo y coherente, se seleccionaron tres indicadores específicos: la tasa de fecundidad adolescente y la población de 0 años desagregada por sexo. Esta selección responde a un criterio demográfico, ya que la fecundidad adolescente constituye un determinante relevante en la dinámica poblacional, mientras que el tamaño de la cohorte infantil permite observar los efectos agregados del comportamiento reproductivo en el tiempo.</p>
<p>El análisis conjunto de estos indicadores permite explorar posibles relaciones entre la evolución de la fecundidad y la estructura etaria temprana en Colombia, facilitando una interpretación más integrada del fenómeno poblacional durante el período 1960–2024. Con el fin de contestar la siguiente pregunta: ¿Existe una relación entre la evolución de la fecundidad adolescente y el tamaño de la cohorte infantil en Colombia desde 1960 hasta 2024?</p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="análisis-de-la-serie-de-tiempo..html#cb31-1" tabindex="-1"></a><span class="co">#Filtremos los 3 indicadores que nos interesan.</span></span>
<span id="cb31-2"><a href="análisis-de-la-serie-de-tiempo..html#cb31-2" tabindex="-1"></a>indicadores_interes <span class="ot">&lt;-</span> <span class="fu">c</span>(</span>
<span id="cb31-3"><a href="análisis-de-la-serie-de-tiempo..html#cb31-3" tabindex="-1"></a>  <span class="st">&quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot;</span>,</span>
<span id="cb31-4"><a href="análisis-de-la-serie-de-tiempo..html#cb31-4" tabindex="-1"></a>  <span class="st">&quot;Age population, age 00, female&quot;</span>,</span>
<span id="cb31-5"><a href="análisis-de-la-serie-de-tiempo..html#cb31-5" tabindex="-1"></a>  <span class="st">&quot;Age population, age 00, male&quot;</span></span>
<span id="cb31-6"><a href="análisis-de-la-serie-de-tiempo..html#cb31-6" tabindex="-1"></a>)</span>
<span id="cb31-7"><a href="análisis-de-la-serie-de-tiempo..html#cb31-7" tabindex="-1"></a></span>
<span id="cb31-8"><a href="análisis-de-la-serie-de-tiempo..html#cb31-8" tabindex="-1"></a>df_3 <span class="ot">&lt;-</span> df_long <span class="sc">%&gt;%</span></span>
<span id="cb31-9"><a href="análisis-de-la-serie-de-tiempo..html#cb31-9" tabindex="-1"></a>  <span class="fu">filter</span>(Series.Name <span class="sc">%in%</span> indicadores_interes)</span></code></pre></div>
<div id="fecundidad-adolescente" class="section level2 hasAnchor" number="3.1">
<h2><span class="header-section-number">3.1</span> Fecundidad adolescente<a href="análisis-de-la-serie-de-tiempo..html#fecundidad-adolescente" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb32"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb32-1"><a href="análisis-de-la-serie-de-tiempo..html#cb32-1" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb32-2"><a href="análisis-de-la-serie-de-tiempo..html#cb32-2" tabindex="-1"></a>  df_3 <span class="sc">%&gt;%</span> </span>
<span id="cb32-3"><a href="análisis-de-la-serie-de-tiempo..html#cb32-3" tabindex="-1"></a>    <span class="fu">filter</span>(Series.Name <span class="sc">==</span> <span class="st">&quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot;</span>),</span>
<span id="cb32-4"><a href="análisis-de-la-serie-de-tiempo..html#cb32-4" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Value)</span>
<span id="cb32-5"><a href="análisis-de-la-serie-de-tiempo..html#cb32-5" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb32-6"><a href="análisis-de-la-serie-de-tiempo..html#cb32-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;#1F4E79&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb32-7"><a href="análisis-de-la-serie-de-tiempo..html#cb32-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb32-8"><a href="análisis-de-la-serie-de-tiempo..html#cb32-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb32-9"><a href="análisis-de-la-serie-de-tiempo..html#cb32-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Adolescent Fertility Rate en Colombia (1960–2024)&quot;</span>,</span>
<span id="cb32-10"><a href="análisis-de-la-serie-de-tiempo..html#cb32-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Año&quot;</span>,</span>
<span id="cb32-11"><a href="análisis-de-la-serie-de-tiempo..html#cb32-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Nacimientos por cada 1.000 mujeres (15–19)&quot;</span></span>
<span id="cb32-12"><a href="análisis-de-la-serie-de-tiempo..html#cb32-12" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range (`geom_line()`).</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-14-1.png" alt="" width="672" /></p>
<p>La tasa de fecundidad adolescente en Colombia presenta una tendencia general descendente entre 1960 y 2024. En los años 60 supera los 110 nacimientos por cada 1.000 mujeres (15–19), disminuye de forma sostenida en los 70 y principios de los 80, y muestra un leve repunte a finales de los 80 y durante los 90.</p>
<p>A partir de los años 2000 la tendencia vuelve a ser claramente decreciente, intensificándose después de 2010 hasta alcanzar valores cercanos a 60 en los años más recientes. En conjunto, el comportamiento del indicador evidencia un cambio estructural en los patrones reproductivos adolescentes, posiblemente asociado a transformaciones demográficas, educativas y en políticas de salud pública.</p>
<div class="sourceCode" id="cb34"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb34-1"><a href="análisis-de-la-serie-de-tiempo..html#cb34-1" tabindex="-1"></a><span class="fu">summary</span>(df_3<span class="sc">$</span>Value[df_3<span class="sc">$</span>Series.Name <span class="sc">==</span> <span class="st">&quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot;</span>])</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA&#39;s 
##   59.47   83.95   90.08   88.19   94.15  115.37       1</code></pre>
<div class="sourceCode" id="cb36"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb36-1"><a href="análisis-de-la-serie-de-tiempo..html#cb36-1" tabindex="-1"></a><span class="fu">sd</span>(df_3<span class="sc">$</span>Value[df_3<span class="sc">$</span>Series.Name <span class="sc">==</span> </span>
<span id="cb36-2"><a href="análisis-de-la-serie-de-tiempo..html#cb36-2" tabindex="-1"></a>   <span class="st">&quot;Adolescent fertility rate (births per 1,000 women ages 15-19)&quot;</span>], </span>
<span id="cb36-3"><a href="análisis-de-la-serie-de-tiempo..html#cb36-3" tabindex="-1"></a>   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 12.68507</code></pre>
<p>El indicador presenta un valor mínimo de 59.47 y un máximo de 115.37 nacimientos por cada 1.000 mujeres adolescentes, lo que evidencia una amplitud considerable en el período analizado.</p>
<p>La media (88.19) es ligeramente inferior a la mediana (90.08), lo que sugiere una leve asimetría negativa, consistente con la tendencia descendente observada en los años más recientes.</p>
<p>El 50% central de los datos se encuentra entre 83.95 (Q1) y 94.15 (Q3), indicando que la mayor parte de los valores históricos se concentró en ese rango.</p>
<p>La desviación estándar de 12.69 indica una dispersión moderada respecto a la media. En términos relativos (CV: Sirve para medir qué tan grande es la variabilidad en relación con el tamaño del promedio≈ 14%), el indicador presenta variabilidad controlada, consistente con una tendencia descendente progresiva más que con fluctuaciones abruptas.</p>
</div>
<div id="población-edad-00-mujeres" class="section level2 hasAnchor" number="3.2">
<h2><span class="header-section-number">3.2</span> Población edad 00 – Mujeres<a href="análisis-de-la-serie-de-tiempo..html#poblaci%C3%B3n-edad-00-mujeres" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb38"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb38-1"><a href="análisis-de-la-serie-de-tiempo..html#cb38-1" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb38-2"><a href="análisis-de-la-serie-de-tiempo..html#cb38-2" tabindex="-1"></a>  df_3 <span class="sc">%&gt;%</span> </span>
<span id="cb38-3"><a href="análisis-de-la-serie-de-tiempo..html#cb38-3" tabindex="-1"></a>    <span class="fu">filter</span>(Series.Name <span class="sc">==</span> <span class="st">&quot;Age population, age 00, female&quot;</span>),</span>
<span id="cb38-4"><a href="análisis-de-la-serie-de-tiempo..html#cb38-4" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Value)</span>
<span id="cb38-5"><a href="análisis-de-la-serie-de-tiempo..html#cb38-5" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb38-6"><a href="análisis-de-la-serie-de-tiempo..html#cb38-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;#4A7A9C&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb38-7"><a href="análisis-de-la-serie-de-tiempo..html#cb38-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-8"><a href="análisis-de-la-serie-de-tiempo..html#cb38-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb38-9"><a href="análisis-de-la-serie-de-tiempo..html#cb38-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Población edad 0 – Mujeres (1960–2024)&quot;</span>,</span>
<span id="cb38-10"><a href="análisis-de-la-serie-de-tiempo..html#cb38-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Año&quot;</span>,</span>
<span id="cb38-11"><a href="análisis-de-la-serie-de-tiempo..html#cb38-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Número de niñas recién nacidas&quot;</span></span>
<span id="cb38-12"><a href="análisis-de-la-serie-de-tiempo..html#cb38-12" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-16-1.png" alt="" width="672" /></p>
<p>La población femenina de edad 0 en Colombia muestra un crecimiento sostenido desde 1960 hasta mediados de la década de 1990, pasando de aproximadamente 325.000 nacimientos a un máximo cercano a 440.000. Este incremento refleja el crecimiento demográfico y los altos niveles de fecundidad del período.</p>
<p>A partir de finales de los años 90 se observa una tendencia descendente progresiva, que se intensifica después de 2010, alcanzando uno de sus niveles más bajos alrededor de 2017. En los años recientes se aprecia una leve recuperación, aunque sin alcanzar los máximos históricos.</p>
<p>En conjunto, el comportamiento evidencia el proceso de transición demográfica del país, caracterizado por una reducción sostenida en los niveles de natalidad.</p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="análisis-de-la-serie-de-tiempo..html#cb39-1" tabindex="-1"></a><span class="fu">summary</span>(df_3<span class="sc">$</span>Value[df_3<span class="sc">$</span>Series.Name <span class="sc">==</span>  <span class="st">&quot;Age population, age 00, female&quot;</span>])</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  323947  350889  369384  377063  402517  437818</code></pre>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="análisis-de-la-serie-de-tiempo..html#cb41-1" tabindex="-1"></a><span class="fu">sd</span>(df_3<span class="sc">$</span>Value[df_3<span class="sc">$</span>Series.Name <span class="sc">==</span> </span>
<span id="cb41-2"><a href="análisis-de-la-serie-de-tiempo..html#cb41-2" tabindex="-1"></a>   <span class="st">&quot;Age population, age 00, female&quot;</span>], </span>
<span id="cb41-3"><a href="análisis-de-la-serie-de-tiempo..html#cb41-3" tabindex="-1"></a>   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 32507.4</code></pre>
<p>La población femenina de edad 0 presenta un valor mínimo de 323.947 y un máximo de 437.818 nacimientos, lo que refleja una variación considerable a lo largo del período analizado.</p>
<p>La media (377.063) es ligeramente superior a la mediana (369.384), lo que indica una leve asimetría positiva, influenciada por los valores más altos registrados durante el pico demográfico de los años 90.</p>
<p>El 50% central de los datos se ubica entre 350.889 (Q1) y 402.517 (Q3), mostrando que la mayoría de los años se concentraron en ese rango. En conjunto, los estadísticos confirman el crecimiento sostenido hasta mediados de los 90 y la posterior disminución observada en el análisis temporal.</p>
<p>La desviación estándar representa aproximadamente el 8.6% de la media, lo que evidencia baja dispersión relativa y confirma un comportamiento demográfico estable en el largo plazo. ## Población edad 00 – Hombres</p>
<div class="sourceCode" id="cb43"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb43-1"><a href="análisis-de-la-serie-de-tiempo..html#cb43-1" tabindex="-1"></a><span class="fu">ggplot</span>(</span>
<span id="cb43-2"><a href="análisis-de-la-serie-de-tiempo..html#cb43-2" tabindex="-1"></a>  df_3 <span class="sc">%&gt;%</span> </span>
<span id="cb43-3"><a href="análisis-de-la-serie-de-tiempo..html#cb43-3" tabindex="-1"></a>    <span class="fu">filter</span>(Series.Name <span class="sc">==</span> <span class="st">&quot;Age population, age 00, male&quot;</span>),</span>
<span id="cb43-4"><a href="análisis-de-la-serie-de-tiempo..html#cb43-4" tabindex="-1"></a>  <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> Value)</span>
<span id="cb43-5"><a href="análisis-de-la-serie-de-tiempo..html#cb43-5" tabindex="-1"></a>) <span class="sc">+</span></span>
<span id="cb43-6"><a href="análisis-de-la-serie-de-tiempo..html#cb43-6" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">&quot;#7BA0B9&quot;</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb43-7"><a href="análisis-de-la-serie-de-tiempo..html#cb43-7" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb43-8"><a href="análisis-de-la-serie-de-tiempo..html#cb43-8" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb43-9"><a href="análisis-de-la-serie-de-tiempo..html#cb43-9" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Población edad 0 – Hombres (1960–2024)&quot;</span>,</span>
<span id="cb43-10"><a href="análisis-de-la-serie-de-tiempo..html#cb43-10" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Año&quot;</span>,</span>
<span id="cb43-11"><a href="análisis-de-la-serie-de-tiempo..html#cb43-11" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;Número de niños recién nacidos&quot;</span></span>
<span id="cb43-12"><a href="análisis-de-la-serie-de-tiempo..html#cb43-12" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="_main_files/figure-html/unnamed-chunk-18-1.png" alt="" width="672" /></p>
<p>La población masculina de edad 0 en Colombia presenta un comportamiento similar al observado en mujeres. Entre 1960 y mediados de los años 90 se evidencia un crecimiento sostenido, pasando de aproximadamente 335.000 nacimientos a un máximo cercano a 455.000.</p>
<p>A partir de finales de los 90 inicia una tendencia descendente progresiva, que se acentúa después de 2010, alcanzando un mínimo alrededor de 2017. Posteriormente se observa una leve recuperación, aunque los niveles recientes permanecen por debajo del pico histórico.</p>
<p>Este patrón confirma el proceso de transición demográfica del país, caracterizado por una disminución estructural en la natalidad.</p>
<div class="sourceCode" id="cb44"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb44-1"><a href="análisis-de-la-serie-de-tiempo..html#cb44-1" tabindex="-1"></a><span class="fu">summary</span>(df_3<span class="sc">$</span>Value[df_3<span class="sc">$</span>Series.Name <span class="sc">==</span>  <span class="st">&quot;Age population, age 00, male&quot;</span>])</span></code></pre></div>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  335109  364271  383633  392092  418678  453895</code></pre>
<div class="sourceCode" id="cb46"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb46-1"><a href="análisis-de-la-serie-de-tiempo..html#cb46-1" tabindex="-1"></a><span class="fu">sd</span>(df_3<span class="sc">$</span>Value[df_3<span class="sc">$</span>Series.Name <span class="sc">==</span> </span>
<span id="cb46-2"><a href="análisis-de-la-serie-de-tiempo..html#cb46-2" tabindex="-1"></a>   <span class="st">&quot;Age population, age 00, male&quot;</span>], </span>
<span id="cb46-3"><a href="análisis-de-la-serie-de-tiempo..html#cb46-3" tabindex="-1"></a>   <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## [1] 33626.59</code></pre>
<p>La población masculina de edad 0 presenta un valor mínimo de 335.109 y un máximo de 453.895 nacimientos, evidenciando una amplitud similar a la observada en mujeres, aunque con niveles consistentemente superiores.</p>
<p>La media (392.092) es ligeramente mayor que la mediana (383.633), lo que indica una leve asimetría positiva, asociada a los valores más altos registrados durante el pico demográfico de los años 90.</p>
<p>El 50% central de los datos se encuentra entre 364.271 (Q1) y 418.678 (Q3), lo que confirma que la mayor parte de los años se concentró en ese intervalo. Estos estadísticos respaldan el patrón de crecimiento sostenido hasta mediados de los 90 y la posterior reducción progresiva de la natalidad.</p>
<p>Con un coeficiente de variación cercano al 8.5%, el indicador presenta una dispersión baja y un patrón altamente consistente a lo largo del tiempo.</p>
<div class="sourceCode" id="cb48"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb48-1"><a href="análisis-de-la-serie-de-tiempo..html#cb48-1" tabindex="-1"></a>df_pct <span class="ot">&lt;-</span> df_3 <span class="sc">%&gt;%</span></span>
<span id="cb48-2"><a href="análisis-de-la-serie-de-tiempo..html#cb48-2" tabindex="-1"></a>  <span class="fu">group_by</span>(Series.Name) <span class="sc">%&gt;%</span></span>
<span id="cb48-3"><a href="análisis-de-la-serie-de-tiempo..html#cb48-3" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb48-4"><a href="análisis-de-la-serie-de-tiempo..html#cb48-4" tabindex="-1"></a>    <span class="at">media_indicador =</span> <span class="fu">mean</span>(Value, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="cb48-5"><a href="análisis-de-la-serie-de-tiempo..html#cb48-5" tabindex="-1"></a>    <span class="at">cambio_pct_media =</span> ((Value <span class="sc">-</span> media_indicador) <span class="sc">/</span> media_indicador) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb48-6"><a href="análisis-de-la-serie-de-tiempo..html#cb48-6" tabindex="-1"></a>  )</span>
<span id="cb48-7"><a href="análisis-de-la-serie-de-tiempo..html#cb48-7" tabindex="-1"></a></span>
<span id="cb48-8"><a href="análisis-de-la-serie-de-tiempo..html#cb48-8" tabindex="-1"></a><span class="fu">ggplot</span>(df_pct, <span class="fu">aes</span>(<span class="at">x =</span> Year, <span class="at">y =</span> cambio_pct_media)) <span class="sc">+</span></span>
<span id="cb48-9"><a href="análisis-de-la-serie-de-tiempo..html#cb48-9" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb48-10"><a href="análisis-de-la-serie-de-tiempo..html#cb48-10" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Series.Name, <span class="at">scales =</span> <span class="st">&quot;free_y&quot;</span>) <span class="sc">+</span></span>
<span id="cb48-11"><a href="análisis-de-la-serie-de-tiempo..html#cb48-11" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb48-12"><a href="análisis-de-la-serie-de-tiempo..html#cb48-12" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb48-13"><a href="análisis-de-la-serie-de-tiempo..html#cb48-13" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">&quot;Cambio porcentual respecto a la media histórica&quot;</span>,</span>
<span id="cb48-14"><a href="análisis-de-la-serie-de-tiempo..html#cb48-14" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">&quot;Año&quot;</span>,</span>
<span id="cb48-15"><a href="análisis-de-la-serie-de-tiempo..html#cb48-15" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">&quot;% respecto a la media&quot;</span></span>
<span id="cb48-16"><a href="análisis-de-la-serie-de-tiempo..html#cb48-16" tabindex="-1"></a>  )</span></code></pre></div>
<pre><code>## Warning: Removed 1 row containing missing values or values outside the scale range (`geom_line()`).</code></pre>
<p><img src="_main_files/figure-html/unnamed-chunk-20-1.png" alt="" width="672" /></p>
<p>El análisis del cambio porcentual respecto a la media permite identificar con mayor claridad los períodos estructuralmente altos y bajos de cada indicador.</p>
<p>En la tasa de fecundidad adolescente, los años 60 se ubican más de 25% por encima del promedio histórico, mientras que a partir de 2010 los valores caen progresivamente hasta situarse cerca de 30% por debajo de la media. Esto confirma un cambio estructural profundo en el comportamiento reproductivo adolescente.</p>
<p>En el caso de la población de edad 0 (mujeres y hombres), los valores se mantienen por debajo de la media en los años 60, superan el promedio durante las décadas de 1980 y 1990 (con picos cercanos al 15%), y posteriormente descienden nuevamente por debajo de la media en los años recientes.</p>
<p>La similitud entre hombres y mujeres evidencia un patrón demográfico consistente, mientras que la mayor amplitud observada en la fecundidad adolescente refleja una transformación más dinámica en ese indicador.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="análisis-univariado..html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="análisis-bivariado.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/03-serietiempo.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

</body>

</html>
